/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/liveness": {
    get: {
      responses: {
        /** @description The service is alive and well */
        200: {
          content: {
            "application/json": {
              /** @description The status of the server */
              status: string;
            };
          };
        };
      };
    };
  };
  "/v1/user": {
    get: {
      responses: {
        /** @description User */
        200: {
          content: {
            "application/json": {
              user?: unknown;
            };
          };
        };
      };
    };
  };
  "/v1/login/github": {
    get: {
      responses: {
        /** @description Redirect to GitHub OAuth */
        302: {
          content: never;
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              error: {
                /**
                 * @description Error code
                 * @enum {string}
                 */
                code: "BAD_REQUEST";
                /** @description Human readable error message */
                message: string;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              error: {
                /**
                 * @description Error code
                 * @enum {string}
                 */
                code: "UNAUTHORIZED";
                /** @description Human readable error message */
                message: string;
              };
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              error: {
                /**
                 * @description Error code
                 * @enum {string}
                 */
                code: "FORBIDDEN";
                /** @description Human readable error message */
                message: string;
              };
            };
          };
        };
        /** @description Not found */
        404: {
          content: {
            "application/json": {
              error: {
                /**
                 * @description Error code
                 * @enum {string}
                 */
                code: "NOT_FOUND";
                /** @description Human readable error message */
                message: string;
              };
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              error: {
                /**
                 * @description Error code
                 * @enum {string}
                 */
                code: "INTERNAL_SERVER_ERROR";
                /** @description Human readable error message */
                message: string;
              };
            };
          };
        };
      };
    };
  };
  "/v1/login/github/callback": {
    get: {
      parameters: {
        path: {
          code: string;
          state: string;
        };
      };
      responses: {
        /** @description Redirect to app */
        302: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
