name = "api"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787
ip = "0.0.0.0"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
